# This is a basic workflow to build and deploy your open textbook with Bookdown.

on:
  push:
    branches: 
      - main

# courtesy of https://github.com/r-lib/actions/blob/v2/examples/bookdown.yaml

name: bookdown

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      #- uses: r-lib/actions/setup-renv@v2
      
      - name: Install R Markdown and Bookdown packages
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
        
      - name: Install TinyTeX
        run: Rscript -e 'tinytex::install_tinytex()'

      - name: Cache bookdown results
        uses: actions/cache@v3
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Build Book
        run: |
          set -ev
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
          
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: _book
